name: Update Slack User Group

on:
  schedule:
    - cron: '0 9 * * 1'  # Ejemplo de cron para ejecutar todos los lunes a las 09:00 UTC

jobs:
  update-slack-user-group:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz
      
      - name: Run the script
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          USER_GROUP_ID: 'S063TADEC77'
        run: python slack_scheduler.py
